# Lecture 1, January 08, 2024

In this lecture, we went over

1. Course syllabus and rules
2. Chapter 1 -- Basic definition of probability. We also saw the potential ambiguities when defining probabilities.

---

::: {.definition name="Classical Definition of probability"}
The **classical** definition: The probability of some event is
\[
\frac{\mathrm{number~of~ways~the~event~can~occur~}}
{\mathrm{{the~total~number~of~possible~outcomes}}},
\]
provided all outcomes are *equally likely*. 
:::

---

::: {.definition name="Relative Frequency Definition of of probability"}

The **relative frequency** definition: The probability of an event
is the (limiting) proportion (or fraction) of times the event occurs in a very
long series of repetitions of an experiment. 
:::

---

::: {.definition name="Subjective Definition of Probability"}
The **subjective** definition: The probability of an event is a measure of how sure the person making the statement is that the event will happen.
:::

---

**Problem**: Each of the above definitions has pitfall:

* Classical: We may not be able to know the total number of possible outcomes, or it may be uncountable
* Relative frequency: We need "repetition", which is often expensive and may not be possible.
* Subjective: We want the probability to be consistent across different people, and and be rigorously defined.