# Lecture 3, January 12, 2024

::: {.definition name="Odds"}
Odds **in favour** of an event $A$ occurring is 
\[
  O(A) := \frac{P(A)}{1-P(A)}.
\]
Odds again an event $A$ is 
\[
  \frac{1-P(A)}{P(A)}.
\]
:::

The range of the odds is $[0,\infty)$. 

It provide a measure of the likelihood of a particular outcome to happen.

Abbreviation: ""p:q".

Note: Probability may be defined through the odds as follow.
\begin{align*}
  &O(A) := \frac{P(A)}{1-P(A)} \\
  &\implies O(A) - P(A)O(A) = P(A) \\
  &\implies O(A) = P(A) (1+O(A)) \\
  &\implies P(A) = \frac{O(A)} {1+O(A)}
\end{align*}

Note: In finite, equally likely sample spaces, computing probabilities amounts to *counting the number of elements in a set*. It will often be difficult to do this manually, so we are looking for clever *counting techniques* in the next chapter. 

--- 

**Chapter 3 Counting Techniques**

Addition rule v.s. Multiplication rule

For addition rule

  * Keyword for addition rule is "**OR**"; 
  * $|A|$ is defined to be the size of the set, aka the cardinality of the set.
  * If $A$ and $B$ are *disjoint* (i.e. $A\cap B = \emptyset$), then $|A\cup B| = |A| + |B|$.
  * $A\cup A^c = S$ where $A \cap A^c = \emptyset$. Thus $|S|=|A|+|A^c|$.

For multiplication rule
  
  * for multiplication rule is "**AND**"
  * An ordered k-tuple is an ordered set of $k$ values: $(a_1,a_2,\dots,a_k)$. If the outcomes in A can be wrttien as an ordered k-tuple where there are $n_1$ choices for $a_1$, $n_2$ choices for $a_2,\dots$ and in general $n_i$ choices for $a_i$, then 
  $$
    |A| = n_1n_2\cdots n_k = \prod_{i=1}^k n_i.
  $$

---

::: {.definition name="Factorial"}
Given $n$ distinct objects, there are 
$$
n! = n \times (n-1) \times \ldots 2 \times 1,
$$
different ordered arrangements of length $n$ that can be made. Note that, we define, $0! = 1$.
:::

* We pronounce $n!$ as "n factorial".
* The following recursive definition is useful:
$$ 
n! = n \cdot (n-1)!
$$
\item When working with factorials, we can often cancel terms, e.g., 
$$ \frac{9!}{7!} = \frac{9\cdot 8 \cdot 7\cdot 6 \cdot \dots \cdot 2 \cdot 1}{7\cdot 6 \cdot \dots \cdot 2 \cdot 1}=9\cdot 8 = 72$$


---
::: {.definition name="Permutation"}
Given $n$ distinct objects, a **permutation** of size $k$ is an $ordered$ subset of $k$ of the individuals. The number of permutations of size $k$ taken from $n$ objects is denoted $n^{(k)}$ and
$$
n^{(k)}=n(n-1)\dots (n-k+1) =\frac{n!}{(n-k)!}.
$$
:::

The tricky part of this definition is the word "ordered". An ordering need not be numerical, for example assigning labels like "President" and "Vice-President" has the effect of ordering the individuals.


## Questions from the class

1. Can we express the odds as $a:b$?

YES. For instance, the example we saw in class (or the clicker question 1), if we roll a fair six sided dice, and let our event $A:=\{\text{# is } 5 \}$. Then the odds $O(A)=\frac{1/6}{1/5}=\frac{1}{5}$. We can see that, there is exactly one possibility we have event $A$, whereas there are 5 possibilities that $A$ does not happen (i.e. the number we roll out is $1,2,3,4,6$). We **can** abbreviate it as "1:5". For a good example of Odds, [WIKI](https://en.wikipedia.org/wiki/Odds) provides a good one.