# Lecture 5, January 17, 2024

Properties of the Binomial coefficients


There are some useful/important results about permutation and combination.

1. $n^{(k)} = n (n - 1)^{(k-1)}$ for $k \geq 1$
2. ${n \choose k} = \frac{n^{(k)}}{k!}$
3. ${n \choose k} = {n \choose n-k}$ for $k \geq 0$
4. ${n \choose k} = {n-1 \choose k-1} + {n-1 \choose k}$
5. Binomial theorem: $(1 + x)^n = \sum_{k=0}^n {n \choose k} x^k$
6. ${n \choose k}$ is equal to the $k$th entry in the $n$th row of **Pascal's triangle**.


Note: Many of these idenetity may be proven using something called *combinatorial proof*. See [Wiki](https://en.wikipedia.org/wiki/Combinatorial_proof) for an (easy) example.

::: {.proof name="4"}

\begin{align*}
{n-1 \choose k-1} + {n-1 \choose k} &= \frac{(n-1)!}{(k-1)! (n-k)!} + \frac{(n-1)!}{k! (n-k-1)!}\\
&= \frac{(n-1)!k }{(k-1)! (n-k)!k} + \frac{(n-1)!(n-k)}{k! (n-k-1)!(n-1)} \\
&= \frac{(n-1)!k + (n-1)! (n-k)}{k! (n-k)!} \\
&- \frac{(n-1)!( k + (n-k))}{k! (n-k)!} \\
&= \frac{(n-1)! n}{k! (n-k)!} \\
&= {n \choose k}
\end{align*}

:::

*** 

Aside: Stirling's formula

$n!$ grows really fast as $n$ increases, so sometimes we need to approximate its value for computational reasons.

**Stirling's formula** provides one such method, and it is given by
    
$$
n! \sim \sqrt{2 \pi n} \left( \frac{n}{e} \right)^n,
$$
where $\sim$ means their ratio approaches 1 as $n$ goes to infinity.

We won't need this approximation, but it's useful to know it exists. 

Example of use:
    Show that  $2^{-2n}\binom{2n}{n} \approx \sqrt{\frac{2}{\pi n}}$
    
*** 


## Example in class

::: {.example name="Application of Stirling's Formula/Approximation for factorial"}
Show that $2^{-2n}{2n \choose n} \approx \sqrt{\frac{1}{\pi n}}$

\begin{align*}
  2^{-2n}{2n \choose n} &= 2^{-2n}\frac{2n!}{n!n!} \\
  &\approx 2^{-2n} \frac{\sqrt{2\pi (2n)} (2n/e)^{2n}}{\sqrt{2\pi n} (n/e)^{n}\sqrt{2\pi n} (n/e)^{n}}\\
  &= 2^{-2n} \frac{\sqrt{4}}{\sqrt{2}\sqrt{2}} \frac{\sqrt{\pi n}}{\sqrt{\pi n}\sqrt{\pi n}} \frac{(2n)^{2n}}{n^n n^n} \frac{e^{-2n}}{e^{-2n}}\\
  &=  2^{-2n} \frac{1}{\sqrt{\pi n}} 2^{2n}\\
  &= \frac{1}{\sqrt{\pi n}} = \sqrt{\frac{1}{\pi n}}
\end{align*}
:::